sonar.projectKey=sistema_contabilidade
sonar.projectName=sistema_contabilidade
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S8445
sonar.issue.ignore.multicriteria.e1.resourceKey=src/test/java/**/*
